// src/utils/flightData.js
export const dummyFlightData = {
  flightsAvailable: [
    // Flight 1: JFK to DEL via KWI (Kuwait Airways, 1 stop, round-trip)
    {
      oneWay: false,
      seatsAvailable: 9,
      currencyCode: "USD",
      basePrice: "246.00",
      totalPrice: "364.77",
      totalTravelers: 1,
      trips: [
        {
          from: "JFK",
          to: "DEL",
          stops: 1,
          totalFlightDuration: "23h 20m",
          totalLayoverDuration: "5h 0m",
          legs: [
            {
              legNo: "1-1",
              flightNumber: "118",
              carrierCode: "KU",
              operatingCarrierCode: "KU",
              aircraftCode: "77W",
              departureAirport: "JFK",
              departureTerminal: "7",
              departureDateTime: "2025-11-14T18:00:00",
              arrivalAirport: "KWI",
              arrivalTerminal: "4",
              arrivalDateTime: "2025-11-15T13:30:00",
              duration: "12h 30m",
              layoverAfter: "5h 0m",
            },
            {
              legNo: "1-2",
              flightNumber: "381",
              carrierCode: "KU",
              operatingCarrierCode: "KU",
              aircraftCode: "32N",
              departureAirport: "KWI",
              departureTerminal: "4",
              departureDateTime: "2025-11-15T18:30:00",
              arrivalAirport: "DEL",
              arrivalTerminal: "3",
              arrivalDateTime: "2025-11-16T00:50:00",
              duration: "4h 20m",
              layoverAfter: null,
            },
          ],
        },
        {
          from: "DEL",
          to: "JFK",
          stops: 1,
          totalFlightDuration: "23h 20m",
          totalLayoverDuration: "5h 0m",
          legs: [
            {
              legNo: "2-1",
              flightNumber: "382",
              carrierCode: "KU",
              operatingCarrierCode: "KU",
              aircraftCode: "32N",
              departureAirport: "DEL",
              departureTerminal: "3",
              departureDateTime: "2025-11-21T02:00:00",
              arrivalAirport: "KWI",
              arrivalTerminal: "4",
              arrivalDateTime: "2025-11-21T04:05:00",
              duration: "4h 35m",
              layoverAfter: "5h 0m",
            },
            {
              legNo: "2-2",
              flightNumber: "117",
              carrierCode: "KU",
              operatingCarrierCode: "KU",
              aircraftCode: "77W",
              departureAirport: "KWI",
              departureTerminal: "4",
              departureDateTime: "2025-11-21T09:05:00",
              arrivalAirport: "JFK",
              arrivalTerminal: "7",
              arrivalDateTime: "2025-11-21T15:50:00",
              duration: "13h 45m",
              layoverAfter: null,
            },
          ],
        },
      ],
      pricingAdditionalInfo: JSON.stringify({
        type: "flight-offer",
        id: "1",
        source: "GDS",
        instantTicketingRequired: false,
        disablePricing: false,
        nonHomogeneous: false,
        oneWay: false,
        paymentCardRequired: false,
        lastTicketingDate: "2025-11-14",
        numberOfBookableSeats: 9,
        itineraries: [
          {
            duration: "PT23H20M",
            segments: [
              {
                departure: { iataCode: "JFK", terminal: "7", at: "2025-11-14T18:00:00" },
                arrival: { iataCode: "KWI", terminal: "4", at: "2025-11-15T13:30:00" },
                carrierCode: "KU",
                number: "118",
                aircraft: { code: "77W" },
                operating: { carrierCode: "KU" },
                duration: "PT12H30M",
                id: "1-1",
                numberOfStops: 0,
                blacklistedInEU: false,
              },
              {
                departure: { iataCode: "KWI", terminal: "4", at: "2025-11-15T18:30:00" },
                arrival: { iataCode: "DEL", terminal: "3", at: "2025-11-16T00:50:00" },
                carrierCode: "KU",
                number: "381",
                aircraft: { code: "32N" },
                operating: { carrierCode: "KU" },
                duration: "PT4H20M",
                id: "1-2",
                numberOfStops: 0,
                blacklistedInEU: false,
              },
            ],
          },
          {
            duration: "PT23H20M",
            segments: [
              {
                departure: { iataCode: "DEL", terminal: "3", at: "2025-11-21T02:00:00" },
                arrival: { iataCode: "KWI", terminal: "4", at: "2025-11-21T04:05:00" },
                carrierCode: "KU",
                number: "382",
                aircraft: { code: "32N" },
                operating: { carrierCode: "KU" },
                duration: "PT4H35M",
                id: "2-1",
                numberOfStops: 0,
                blacklistedInEU: false,
              },
              {
                departure: { iataCode: "KWI", terminal: "4", at: "2025-11-21T09:05:00" },
                arrival: { iataCode: "JFK", terminal: "7", at: "2025-11-21T15:50:00" },
                carrierCode: "KU",
                number: "117",
                aircraft: { code: "77W" },
                operating: { carrierCode: "KU" },
                duration: "PT13H45M",
                id: "2-2",
                numberOfStops: 0,
                blacklistedInEU: false,
              },
            ],
          },
        ],
        price: {
          currency: "USD",
          total: "364.77",
          base: "246.00",
          fees: [
            { amount: "0.00", type: "SUPPLIER" },
            { amount: "0.00", type: "TICKETING" },
          ],
          grandTotal: "364.77",
        },
        pricingOptions: {
          includedCheckedBagsOnly: true,
          fareType: ["PUBLISHED"],
          refundableFare: false,
          noRestrictionFare: false,
          noPenaltyFare: false,
        },
        validatingAirlineCodes: ["KU"],
        travelerPricings: [
          {
            travelerId: "1",
            fareOption: "STANDARD",
            travelerType: "ADULT",
            price: { currency: "USD", total: "364.77", base: "246.00" },
            fareDetailsBySegment: [
              {
                segmentId: "1-1",
                cabin: "ECONOMY",
                fareBasis: "VOWIN1",
                class: "V",
                isAllotment: false,
                includedCheckedBags: { quantity: 2, weight: 0 },
              },
              {
                segmentId: "1-2",
                cabin: "ECONOMY",
                fareBasis: "VOWIN1",
                class: "V",
                isAllotment: false,
                includedCheckedBags: { quantity: 2, weight: 0 },
              },
              {
                segmentId: "2-1",
                cabin: "ECONOMY",
                fareBasis: "VOWIN1",
                class: "V",
                isAllotment: false,
                includedCheckedBags: { quantity: 2, weight: 0 },
              },
              {
                segmentId: "2-2",
                cabin: "ECONOMY",
                fareBasis: "VOWIN1",
                class: "V",
                isAllotment: false,
                includedCheckedBags: { quantity: 2, weight: 0 },
              },
            ],
          },
        ],
      }),
    },
    // Flight 2: JFK to DEL via DOH (Qatar Airways, 1 stop, one-way)
    {
      oneWay: true,
      seatsAvailable: 7,
      currencyCode: "USD",
      basePrice: "350.00",
      totalPrice: "480.50",
      totalTravelers: 1,
      trips: [
        {
          from: "JFK",
          to: "DEL",
          stops: 1,
          totalFlightDuration: "20h 45m",
          totalLayoverDuration: "3h 30m",
          legs: [
            {
              legNo: "1-1",
              flightNumber: "702",
              carrierCode: "QR",
              operatingCarrierCode: "QR",
              aircraftCode: "351",
              departureAirport: "JFK",
              departureTerminal: "8",
              departureDateTime: "2025-11-14T21:00:00",
              arrivalAirport: "DOH",
              arrivalTerminal: "1",
              arrivalDateTime: "2025-11-15T17:15:00",
              duration: "12h 15m",
              layoverAfter: "3h 30m",
            },
            {
              legNo: "1-2",
              flightNumber: "578",
              carrierCode: "QR",
              operatingCarrierCode: "QR",
              aircraftCode: "359",
              departureAirport: "DOH",
              departureTerminal: "1",
              departureDateTime: "2025-11-15T20:45:00",
              arrivalAirport: "DEL",
              arrivalTerminal: "3",
              arrivalDateTime: "2025-11-16T02:45:00",
              duration: "4h 0m",
              layoverAfter: null,
            },
          ],
        },
      ],
      pricingAdditionalInfo: JSON.stringify({
        type: "flight-offer",
        id: "2",
        source: "GDS",
        instantTicketingRequired: false,
        disablePricing: false,
        nonHomogeneous: false,
        oneWay: true,
        paymentCardRequired: false,
        lastTicketingDate: "2025-11-14",
        numberOfBookableSeats: 7,
        itineraries: [
          {
            duration: "PT20H45M",
            segments: [
              {
                departure: { iataCode: "JFK", terminal: "8", at: "2025-11-14T21:00:00" },
                arrival: { iataCode: "DOH", terminal: "1", at: "2025-11-15T17:15:00" },
                carrierCode: "QR",
                number: "702",
                aircraft: { code: "351" },
                operating: { carrierCode: "QR" },
                duration: "PT12H15M",
                id: "1-1",
                numberOfStops: 0,
                blacklistedInEU: false,
              },
              {
                departure: { iataCode: "DOH", terminal: "1", at: "2025-11-15T20:45:00" },
                arrival: { iataCode: "DEL", terminal: "3", at: "2025-11-16T02:45:00" },
                carrierCode: "QR",
                number: "578",
                aircraft: { code: "359" },
                operating: { carrierCode: "QR" },
                duration: "PT4H0M",
                id: "1-2",
                numberOfStops: 0,
                blacklistedInEU: false,
              },
            ],
          },
        ],
        price: {
          currency: "USD",
          total: "480.50",
          base: "350.00",
          fees: [
            { amount: "0.00", type: "SUPPLIER" },
            { amount: "0.00", type: "TICKETING" },
          ],
          grandTotal: "480.50",
        },
        pricingOptions: {
          includedCheckedBagsOnly: true,
          fareType: ["PUBLISHED"],
          refundableFare: false,
          noRestrictionFare: false,
          noPenaltyFare: false,
        },
        validatingAirlineCodes: ["QR"],
        travelerPricings: [
          {
            travelerId: "1",
            fareOption: "STANDARD",
            travelerType: "ADULT",
            price: { currency: "USD", total: "480.50", base: "350.00" },
            fareDetailsBySegment: [
              {
                segmentId: "1-1",
                cabin: "ECONOMY",
                fareBasis: "NOWIN1",
                class: "N",
                isAllotment: false,
                includedCheckedBags: { quantity: 2, weight: 0 },
              },
              {
                segmentId: "1-2",
                cabin: "ECONOMY",
                fareBasis: "NOWIN1",
                class: "N",
                isAllotment: false,
                includedCheckedBags: { quantity: 2, weight: 0 },
              },
            ],
          },
        ],
      }),
    },
    // Flight 3: EWR to DEL via LHR (British Airways, 1 stop, round-trip
        ],
};